language: python
python:
  - "3.3"
services:
  - elasticsearch
addons:
  postgresql: "9.3"
notifications:
  email:
    recipients:
      - derek.kai.chun.kwok@gmail.com
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
before_script:
  - cp config/travis/localsettings.py channel2/localsettings.py
script:
  - python manage.py test --verbosity 2
